# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab83c5dc540b716e8d30bca311f026b7b78f98e0d372b4787d85d75654eefef939dfec3095705ba56528a72fcf317b0e105679b88c8b4e9812a9cdca1eb8ac4

test:
  secret_key_base: bae144db2ef31f66c91f61a61f46fe398495e2f8fe47c4a768886a5e584d59491ee8956d43496ac29ab1cda2da3448105aaa9b520f4df2d9b8793256ababe1d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bae144db2ef31f66c91f61a61f46fe398495e2f8fe47c4a768886a5e584d59491ee8956d43496ac29ab1cda2da3448105aaa9b520f4df2d9b8793256ababe1d9
